version: "3.7"
services:
  app:
    build:
      args:
        user: craig
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: chess-php-docker
    container_name: chess-php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - chess-php

  db:
    image: mysql:5.7
    container_name: chess-php-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chess
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_PASSWORD: abc123
      MYSQL_USER: craig
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - chess-php-db-data:/var/lib/mysql:rw
    networks:
      - chess-php

  nginx:
    image: nginx:alpine
    container_name: chess-php-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - chess-php

networks:
  chess-php:
    driver: bridge

#Volumes
volumes:
  chess-php-db-data:
    driver: local
